### PR TITLE
TWP-66 Test if slice is defined. If not, use other way to forward events

### PR DESCRIPTION
**Pull request by sebbeaume**

### CODE REVIEW

**Comment by johache** [comment]
Are you sure of this ?
Did you run the code ? Did you check the hints I gave you ?

**Comment by sebbeaume** [comment]
Yes i ran the code. I checked the hints : i think testing both typeof === string and slice != undefined is not useful. Only testing that slice is not undefined is enough IMO.

**Comment by johache** [comment]
Just checked out the code, are you REALLY sure it works ?
Did you run any test ?

**Comment by johache** [comment]
LGTM, good job.

**Pull request merged**
