### PR TITLE
Propagate gUM to window and to AdapterJS

### PR DESCRIPTION
**Pull request by johache**
Fixes SkylinkJS test async

### CODE REVIEW

**Comment by letchoo** [comment]
## Tested with `adapter.screenshare.js` file.

**Firefox**
- (F) `getUserMedia()` && `window.getUserMedia()`: Not using `adapter.screenshare` overrides. It was using `webrtc/adapter` one.
- (P) `navigator.getUserMedia()` && `window.navigator.getUserMedia()`: It was using `adapter.screenshare` overrides.
- (F) `navigator.mediaDevices.getUserMedia()` && `window.navigator.mediaDevices.getUserMedia()`: Not using `adapter.screenshare` overrides. It was not modified at all or polyfilled.

**Chrome / Opera**
- (F) `getUserMedia()` && `window.getUserMedia()`: Not using `adapter.screenshare` overrides. It was using `webrtc/adapter` one.
- (P) `navigator.getUserMedia()` && `window.navigator.getUserMedia()`: It was using `adapter.screenshare` overrides.
- (F) `navigator.mediaDevices.getUserMedia()` && `window.navigator.mediaDevices.getUserMedia()`: Not using `adapter.screenshare` overrides.

**Safari**
- (F) `getUserMedia()` && `window.getUserMedia()`: It is `null`.
```
TypeError: null is not an object (evaluating 'window.getUserMedia.toString')
TypeError: null is not an object (evaluating 'getUserMedia.toString')
```
- (P) `navigator.getUserMedia()` && `window.navigator.getUserMedia()`: It was using `adapter.screenshare` overrides.
- (F) `navigator.mediaDevices.getUserMedia()` && `window.navigator.mediaDevices.getUserMedia()`: Not using `adapter.screenshare` overrides.

Some of the changes might be resolved in PR #170.

**Comment by letchoo** [comment]
Opera does not allow screensharing, which is a pass for that part.

**Comment by johache** [comment]
@letchoo Should be fixed now, please test again :)

**Comment by letchoo** [comment]
@johache Please revise the following errors below. I'll continuing adding tests for Promises. For now, testing on IE is on hold because Promises is not implemented on IE yet.

### Testing the `adapter.screenshare.js` file.
**Firefox**
- (P) `getUserMedia()` && `window.getUserMedia()` -> 
- (P) `navigator.getUserMedia()` && `window.navigator.getUserMedia()`
- (P) `navigator.mediaDevices.getUserMedia()` && `window.navigator.mediaDevices.getUserMedia()`

**Chrome**
- (P) `getUserMedia()` && `window.getUserMedia()`
- (P) `navigator.getUserMedia()` && `window.navigator.getUserMedia()`
- (P) `navigator.mediaDevices.getUserMedia()` && `window.navigator.mediaDevices.getUserMedia()`

@johache btw there's an error that it states that `Error: Current browser does not support screensharing` when this error is supposed to be thrown for Opera browsers. It's likely `webrtcDetectedBrowser` is not defined. We probably might need to figure a way to make browserify work with `webrtcDetectedBrowser`, `webrtcDetectedVersion` and `webrtcMinimumVersion`. It's probably the `webrtc/adapter` that caused it.

**Opera**
- (P) `getUserMedia()` && `window.getUserMedia()` -> 
- (P) `navigator.getUserMedia()` && `window.navigator.getUserMedia()`
- (P) `navigator.mediaDevices.getUserMedia()` && `window.navigator.mediaDevices.getUserMedia()`

**Safari**
- (F) `getUserMedia()` && `window.getUserMedia()`
<br>It's currently pointing to the native getUserMedia without any screensharing polyfills.
- (P) `navigator.getUserMedia()` && `window.navigator.getUserMedia()`
- (F) `navigator.mediaDevices.getUserMedia()` && `window.navigator.mediaDevices.getUserMedia()`
<br>It's because `getUserMedia()` doesn't have the screensharing polyfills.

----
### Testing the `adapter.debug.js` file.
**Firefox**
- (P) `getUserMedia()` && `window.getUserMedia()`
- (P) `navigator.getUserMedia()` && `window.navigator.getUserMedia()`
- (F) `navigator.mediaDevices.getUserMedia()` && `window.navigator.mediaDevices.getUserMedia().<br>It's currently pointing to the native getUserMedia without any polyfills.

**Chrome**
- (P) `getUserMedia()` && `window.getUserMedia()`
- (P) `navigator.getUserMedia()` && `window.navigator.getUserMedia()`
- (P) `navigator.mediaDevices.getUserMedia()` && `window.navigator.mediaDevices.getUserMedia()`

**Opera**
- (P) `getUserMedia()` && `window.getUserMedia()`
- (P) `navigator.getUserMedia()` && `window.navigator.getUserMedia()`
- (P) `navigator.mediaDevices.getUserMedia()` && `window.navigator.mediaDevices.getUserMedia()`

**Safari**
- (P) `getUserMedia()` && `window.getUserMedia()`
- (P) `navigator.getUserMedia()` && `window.navigator.getUserMedia()`
- (P) `navigator.mediaDevices.getUserMedia()` && `window.navigator.mediaDevices.getUserMedia()`

**Comment by letchoo** [comment]
## Testing the Promises
NOTE: IN-PROGRESS. Don't revise yet because there is required fixes for the failure above before testing.

### How are we testing the Promises
Using the `navigator.mediaDevices.getUserMedia()`.

**Navigation Reject**
Invoke first with `{ audio: true, video: false }` and then reject the permission

**Navigation Invalid Constraints**
Invoke with `{ audio: false, video: false }` and then reject the permission

**Navigation Success**
Invoke with `{ audio: true, video: true }` and then access the permission

_Example code:_
```
navigator.mediaDevices.getUserMedia({ video: false, audio: true }).then(function(mediaStream) { console.info(mediaStream); }).catch(function(error) { throw error; });
```
----
I'm new to Promise but according to the specs, I'm following it. [Docs](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise)

### Testing the `adapter.screenshare.js` file.
**Firefox**
- 

**Safari**
- (F) Navigation Reject -> Does not throw any error.
- (F) Navigation Invalid Constraints -> Does not throw any error but displays a Plugin prompt of both None. It seems like pressing ok gives me an "MediaStream" object which is not a correct case since both Firefox and Chrome throws an error on that part.
- (P) Navigation Success

----
----
## Testing the `getUserMedia()` function definition

**Comment by johache** [comment]
Regarding your last post: I don;t think this had anything to do with this PR. If you think this is relevant, please create a JIRA ticket.

However: if you change your code for

```
navigator.mediaDevices.getUserMedia({ video: false, audio: true }).then(function(mediaStream) { console.info(mediaStream); }).catch(function(error) { console.log('failure'); });
```

*Navigation reject* does log 'failure'. The throw probably just doesn;t pop out of the catch.
*Navigation invalid constraints* : I don't believe the spec expect constraints to have at least one of audio/video. Chrome and FF chose to throw an error, I think it's more relevant to just return an empty stream. Can be useful for some use cases (track aggregation for example). Spec: https://www.w3.org/TR/mediacapture-streams/#idl-def-MediaStreamConstraints

So I don't think that a ticket is relevant either.

**Comment by johache** [comment]
Fixed the Safari adapter.screenshare.js issues.
There is no issue with adapter.debug.js on FF. `navigator.mediaDevices.getUserMedia` is natively implemented on newer version, thus the use of the native code.

**Comment by letchoo** [comment]
@johache sure. I think we can have a separate PR for promises. We can close the tests if needed.
My suggestion is that audio: false and video: false does not make any sense since you want to get the media and you ask for false. But it's up to you to decide the behaviour. I just suggest because it might be confusing since we are not consistent with what is implemented out there.

**Comment by johache** [comment]
I do see the inconsistency, but I don't thinks that's a problem since it just adds up possibilities, not remove any. If you want to check for error, you can still check that the stream has tracks after receiving it.

**Comment by letchoo** [comment]
@johache for the Firefox native part, I think that's an issue since the `navigator.getUserMedia` and `getUserMedia` uses the Firefox polyfill done by `webrtc/adapter`. We can wait for them to polyfill it, but it's still an issue.

**Comment by johache** [comment]
Not an issue. 
- gUM is polyfills only for FF < 38 anyway
- If old FF (no native support of mediaDevice.getUserMedia), then the call is redirected to the polyfill,
- if new FF (native support of mediaDevice.getUserMedia), there would be no polyfill anyway

That is the logic in webrtc-adapter, I suggest we follow it.

Can we merge this PR ?

**Comment by letchoo** [comment]
@johache noted. We can merge the PR.

**Pull request merged**
