### PR TITLE
AJS-286 supporting constraint format for device id in webrtcSamples

### PR DESCRIPTION
**Pull request by miniruwan**
Refer the [ticket ](https://jira.temasys.com.sg/browse/AJS-286) for details

### CODE REVIEW

**Comment by letchoo** [comment]
@miniruwan I suggest not setting `r.exact = undefined;` unless if there is a reason for this?

**Comment by johache** [comment]
LGTM, except for the indenting.
Please use 2 spaces indent. You can merge after that.

**Comment by miniruwan** [comment]
[**@letchoo**](https://github.com/letchoo) commented on [2017 M05 23 17:53 GMT+8](https://github.com/Temasys/AdapterJS/pull/266#issuecomment-303349451 "2017-05-23T09:53:01Z - Replied by Github Reply Comments"):
> @miniruwan I suggest not setting `r.exact = undefined;` unless if there is a reason for this?

This is intentional @letchoo. This is to avoid getting into the if condition below
`if (r.exact !== undefined && typeof r.exact !== 'number')`

**Comment by miniruwan** [comment]
[**@johache**](https://github.com/johache) commented on [2017 M05 24 10:10 GMT+8](https://github.com/Temasys/AdapterJS/pull/266#issuecomment-303598049 "2017-05-24T02:10:45Z - Replied by Github Reply Comments"):
> LGTM, except for the indenting.
> Please use 2 spaces indent. You can merge after that.

done.

**Pull request merged**
