### PR TITLE
TWP-396: Splitting new and old constructors for RTCPeerConnection

### PR DESCRIPTION
**Pull request by johache**
The next plugin version supports a new constructor more in line with the specs
https://www.w3.org/TR/webrtc/#widl-ctor-RTCPeerConnection--RTCConfiguration-configuration

This 
* calls the new constructor if it is available, 
* call the previous constructor otherwise

### CODE REVIEW

**Comment by letchoo** [comment]
Tested with Chrome and Safari.
The errors were thrown, but it seems that it might be advisable for us to throw our errors instead of `undefined is not an object (evaluating 'iceServers.length')`.

**Chrome**
> new webkitRTCPeerConnection(null)
RTCPeerConnection {}
new webkitRTCPeerConnection(null, {})
RTCPeerConnection {}
new webkitRTCPeerConnection(null, null)
RTCPeerConnection {}
new webkitRTCPeerConnection(null, null, null)
RTCPeerConnection {}
new webkitRTCPeerConnection({})
VM505:2 Uncaught TypeError: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration(…)(anonymous function) @ VM505:2InjectedScript._evaluateOn @ VM376:875InjectedScript._evaluateAndWrap @ VM376:808InjectedScript.evaluate @ VM376:664
new webkitRTCPeerConnection({ iceServers: []})
RTCPeerConnection {}
new webkitRTCPeerConnection({ iceServers: null})
VM507:2 Uncaught TypeError: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration(…)(anonymous function) @ VM507:2InjectedScript._evaluateOn @ VM376:875InjectedScript._evaluateAndWrap @ VM376:808InjectedScript.evaluate @ VM376:664
new webkitRTCPeerConnection({ iceServers: '' })
VM508:2 Uncaught TypeError: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration(…)(anonymous function) @ VM508:2InjectedScript._evaluateOn @ VM376:875InjectedScript._evaluateAndWrap @ VM376:808InjectedScript.evaluate @ VM376:664
new webkitRTCPeerConnection({ iceServers: true })
VM543:2 Uncaught TypeError: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration(…)(anonymous function) @ VM543:2InjectedScript._evaluateOn @ VM376:875InjectedScript._evaluateAndWrap @ VM376:808InjectedScript.evaluate @ VM376:664
new webkitRTCPeerConnection({ iceServers: [] })
RTCPeerConnection {}

**Safari**
> > new RTCPeerConnection(null)
< <JSAPI-Auto Javascript Object>
> new RTCPeerConnection(null, null)
< <JSAPI-Auto Javascript Object>
> new RTCPeerConnection(null, null, null)
< <JSAPI-Auto Javascript Object>
> new RTCPeerConnection({})
< TypeError: undefined is not an object (evaluating 'iceServers.length')

> new RTCPeerConnection({ iceServers: [] })
< <JSAPI-Auto Javascript Object>
> new RTCPeerConnection({ iceServers: null })
< TypeError: null is not an object (evaluating 'iceServers.length')

> new RTCPeerConnection({ iceServers: '' })
< Error: Error calling method on NPObject.

> new RTCPeerConnection({ iceServers: true })
< Error: Error calling method on NPObject.

> new RTCPeerConnection({ iceServers: [] })
< <JSAPI-Auto Javascript Object>

**Comment by johache** [comment]
@letchoo 
* The PR code never runs on Chrome. It's plugin only, so IE and Safari
* added custom throw to detect as much as possible bad arguments

**Comment by letchoo** [comment]
@johache, noted. Just wanted to use Chrome as an example to ensure we follow the same conventions with other browsers.

**Comment by johache** [comment]
The spec doesn;t say so, but I agree, let's align on Chrome and FF.
Corrected again.

Spec: https://www.w3.org/TR/webrtc/#rtcpeerconnection-interface

**Comment by johache** [comment]
Updated with isArray, tested successfully on IE 9

**Comment by letchoo** [comment]
Ok. Just saw this [commit line](https://github.com/Temasys/AdapterJS/commit/eb0fc219f07c398021deb86450e9002386890370#diff-b1ee9bbe2f0ee05f1717e6f3fe0187d7R919), and just checking if servers is `null` or `"string"` or `false` or undefined object, does the plugin handles it. Just checking incase.

**Comment by johache** [comment]
1. Just saw this commit line, and just checking if servers is null or "string" or false or undefined object, does the plugin handles it. Just checking incase.
-> this is caught by the lines over: https://github.com/Temasys/AdapterJS/commit/eb0fc219f07c398021deb86450e9002386890370#diff-b1ee9bbe2f0ee05f1717e6f3fe0187d7R910


2. It seems like according to the logic as stated new RTCPeerConnection(), new RTCPeerConnection("erer"), new RTCPeerConnection(false) will pass, but does not make sense for the other two (Firefox allows new RTCPeerConnection()).
-> all these lines are only plugin related. FF and Chrome never pass there

3.
Suggestion is to use if (typeof servers !== 'object' || (typeof servers === 'object' && servers !== null && !Array.isArray(servers.iceServers))).
then what ? where does this go? what is the semantic ?

**Comment by letchoo** [comment]
@johache actually if you put `new RTCPeerConnection(true)` or `new RTCPeerConnection(1)` it will fail.

Since `true` or `1` is a truthy.
For the case of `new webkitRTCPeerConnection(true)`.

**Chrome**
> VM166:2 Uncaught TypeError: Failed to construct 'RTCPeerConnection': parameter 1 ('rtcConfiguration') is not an object.(…)

**Firefox**
> TypeError: Argument 1 of mozRTCPeerConnection.constructor can't be converted to a dictionary.

**Safari**
> TypeError: undefined is not an object (evaluating 'iceServers.length')

Hence the logic for that.

**Comment by johache** [comment]
@letchoo I have changed the condition to something that makes more sense (pure semantic description)

We spent too much time looking for it though. So I suggest we add the tests you described in your previous comments, and only then merge this branch.
I'll be doing that tomorrow.

**Comment by johache** [comment]
@letchoo : Updated tests, can you have a new look ?

**Comment by letchoo** [comment]
Tested manually:

**(PASS) new RTCPeerConnection()**
> [JSAPI-Auto Javascript Object]

**(PASS) new RTCPeerConnection(null)**
> [JSAPI-Auto Javascript Object]

**(PASS) new RTCPeerConnection("test")**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection(1)**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection(0)**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection(true)**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection(false)**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection([])**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection({})**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection({ iceServers: null })**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection({ iceServers: "test" })**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection({ iceServers: 1 })**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection({ iceServers: 0 })**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection({ iceServers: true })**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection({ iceServers: false })**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection({ iceServers: [] })**
> [JSAPI-Auto Javascript Object]

**(?FAILED) new RTCPeerConnection({ iceServers: [1,] })**
May not be important since it's plugin failure
> Error: Error calling method on NPObject.

**(?FAILED) new RTCPeerConnection({ iceServers: [], garbage: "test" })**
Should throw an error in Chrome's, but not of importance
> [JSAPI-Auto Javascript Object]

**(?FAILED) new RTCPeerConnection({ iceServers: [], garbage: "test" }, null)**
Should throw an error in Chrome's, but not of importance
> [JSAPI-Auto Javascript Object]

**(?FAILED) new RTCPeerConnection({ iceServers: [], garbage: "test" }, {})**
> [JSAPI-Auto Javascript Object]

**(?FAILED) new RTCPeerConnection({ iceServers: [], garbage: "test" }, { test: "x" })**
> [JSAPI-Auto Javascript Object]

**(?FAILED) new RTCPeerConnection({ iceServers: [], garbage: "test" }, { optional: 1 })**
May not be important since it's plugin failure
> Error: Error calling method on NPObject.

**(?FAILED) new RTCPeerConnection({ iceServers: [], garbage: "test" }, { optional: 2 })**
May not be important since it's plugin failure
> Error: Error calling method on NPObject.

**(PASS) new RTCPeerConnection({ iceServers: [], garbage: "test" }, { optional: [] })**
May not be important since it's plugin failure
> [JSAPI-Auto Javascript Object]

**(?FAILED) new RTCPeerConnection({ iceServers: [], garbage: "test" }, { optional: {} })**
May not be important since it's plugin failure
> Error: Error calling method on NPObject.

**(FAILED) new RTCPeerConnection({ iceServers: [], garbage: "test" }, 1)**
Should throw an Error.
> [JSAPI-Auto Javascript Object]

**(FAILED) new RTCPeerConnection({ iceServers: [], garbage: "test" }, 2)**
Should throw an Error.
> [JSAPI-Auto Javascript Object]

**(FAILED) new RTCPeerConnection({ iceServers: [], garbage: "test" }, "erer")**
Should throw an Error.
> [JSAPI-Auto Javascript Object]

**(FAILED) new RTCPeerConnection({ iceServers: [], garbage: "test" }, true)**
Should throw an Error.
> [JSAPI-Auto Javascript Object]

**(FAILED) new RTCPeerConnection({ iceServers: [], garbage: "test" }, false)**
Should throw an Error.
> [JSAPI-Auto Javascript Object]

**(PASS) new RTCPeerConnection({ iceServers: [], garbage: "test" }, [])
> [JSAPI-Auto Javascript Object]

Tested and it seems to be looking good. Note that those failures are also checked upon against Chrome and Firefox. They throw an Error. The ones with (?) we can generally ignore since they are not so important.

@johache It's your decision if you want to implement those checks.

**Comment by letchoo** [comment]
@johache, I've added checks and additional tests for these constraints.

See branch: [TWP-396-as-a-plugin-user-i-want-rtcpeerc-additional-tests](https://github.com/Temasys/AdapterJS/compare/TWP-396-as-a-plugin-user-i-want-rtcpeerc-additional-tests)

Tested manually:

**(PASS) new RTCPeerConnection()**
> [JSAPI-Auto Javascript Object]

**(PASS) new RTCPeerConnection(null)**
> [JSAPI-Auto Javascript Object]

**(PASS) new RTCPeerConnection("test")**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection(1)**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection(0)**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection(true)**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection(false)**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection([])**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection({})**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection({ iceServers: null })**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection({ iceServers: "test" })**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection({ iceServers: 1 })**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection({ iceServers: 0 })**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection({ iceServers: true })**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection({ iceServers: false })**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection({ iceServers: [] })((
> [JSAPI-Auto Javascript Object]

**(PASS) new RTCPeerConnection({ iceServers: [] }, null)**
> [JSAPI-Auto Javascript Object]

**(PASS) new RTCPeerConnection({ iceServers: [] }, undefined)**
> [JSAPI-Auto Javascript Object]

**(PASS) new RTCPeerConnection({ iceServers: [] }, {})**
> [JSAPI-Auto Javascript Object]

**(PASS) new RTCPeerConnection({ iceServers: [] }, { test: "x" })**
> [JSAPI-Auto Javascript Object]

**(PASS) new RTCPeerConnection({ iceServers: [] }, 1)**
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, 2)**
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, true)**
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, false)**
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, 0)**
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, [])**
> [JSAPI-Auto Javascript Object]

**(PASS) new RTCPeerConnection({ iceServers: [] }, { optional: [] })**
> [JSAPI-Auto Javascript Object]

**(PASS) new RTCPeerConnection({ iceServers: [] }, { optional: "test" })**
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, { optional: 1 })**
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, { optional: 0 })**
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, { optional: true })**
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, { optional: false })**
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, { optional: {} })**
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, { optional: null })**
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, { optional: undefined })**
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(SKIP) new RTCPeerConnection({ iceServers: [], garbage: "test" })**
Not sure if you want to add checks for this

**(SKIP) new RTCPeerConnection({ iceServers:[1,] })**
Not sure if you want to add checks for this

**Comment by johache** [comment]
@letchoo :
Merged you branch into the original one, and added a todo. Not ready to merge in dev yet. Will get back to it later.

**Comment by johache** [comment]
@letchoo updated, you can start validating.
We should add tests for constraints.mandatory as well.

**Comment by letchoo** [comment]
@johache I've tested manually already.

**(PASS) new RTCPeerConnection()**
> [JSAPI-Auto Javascript Object]

**(PASS) new RTCPeerConnection(null)**
> [JSAPI-Auto Javascript Object]

**(PASS) new RTCPeerConnection("test")**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection(1)
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection(0)
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection(true)
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection(false)
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection([])
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection({})
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection({ iceServers: null })
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection({ iceServers: "test" })
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection({ iceServers: 1 })
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection({ iceServers: 0 })
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection({ iceServers: true })
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection({ iceServers: false })
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection({ iceServers: [] })
> [JSAPI-Auto Javascript Object]

**(PASS) new RTCPeerConnection({ iceServers: [] }, null)
> [JSAPI-Auto Javascript Object]

**(PASS) new RTCPeerConnection({ iceServers: [] }, undefined)
> [JSAPI-Auto Javascript Object]

**(PASS) new RTCPeerConnection({ iceServers: [] }, {})
> [JSAPI-Auto Javascript Object]

**(PASS) new RTCPeerConnection({ iceServers: [] }, { test: "x" })
> [JSAPI-Auto Javascript Object]

**(PASS) new RTCPeerConnection({ iceServers: [] }, 1)
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, 2)
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, true)
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, false)
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, 0)
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, [])
> [JSAPI-Auto Javascript Object]

**(PASS) new RTCPeerConnection({ iceServers: [] }, { optional: [] })
> [JSAPI-Auto Javascript Object]

**(PASS) new RTCPeerConnection({ iceServers: [] }, { optional: "test" })
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, { optional: 0 })
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, { optional: 1 })
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, { optional: true })
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, { optional: false })
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, { optional: {} })
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, { optional: null })
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, { optional: undefined })
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, { mandatory: {} })
> <JSAPI-Auto Javascript Object> = $10

**(PASS) new RTCPeerConnection({ iceServers: [] }, { mandatory: [] })
> [JSAPI-Auto Javascript Object]

**(PASS) new RTCPeerConnection({ iceServers: [] }, { mandatory: "test" })
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, { mandatory: 1 })
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, { mandatory: 0 })
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, { mandatory: {} })
> [JSAPI-Auto Javascript Object]

**(FAIL) new RTCPeerConnection({ iceServers: [] }, { mandatory: null })
> [JSAPI-Auto Javascript Object]

**(PASS) new RTCPeerConnection({ iceServers: [] }, { mandatory: undefined })
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, { optional: "test", mandatory: [] })
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, { optional: [], mandatory: "test" })
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, { optional: [], mandatory: {} })
> [JSAPI-Auto Javascript Object]

**(FAIL) new RTCPeerConnection({ iceServers: [] }, { optional: [], mandatory: null })
> [JSAPI-Auto Javascript Object]

**Comment by johache** [comment]
I don;t see anything wrong with 

**(FAIL) new RTCPeerConnection({ iceServers: [] }, { mandatory: null })
[JSAPI-Auto Javascript Object]

and

**(FAIL) new RTCPeerConnection({ iceServers: [] }, { optional: [], mandatory: null })
[JSAPI-Auto Javascript Object]


{mandatory: null} is semantically the same as {}, right ?

**Comment by letchoo** [comment]
@johache semantically, it's correct to say it's typeof `"object"`, but it terms of truthy and falsely, `null` is false and `{}` is true.

You may try in Chrome 48 to see that it fails

**Comment by johache** [comment]
Added the tests to karma.
On this, I would say that this is an error on Chrome's end.

**Comment by letchoo** [comment]
@johache it's up to you to decide to implement this in. Seeing `optional` throwing error for `null` would not make sense for `mandatory` to be fine with it.

**Comment by johache** [comment]
Correct, updated that.

**Comment by letchoo** [comment]
@johache I've updated it.

**(PASS) new RTCPeerConnection()**
> [JSAPI-Auto Javascript Object]

**(PASS) new RTCPeerConnection(null)**
> [JSAPI-Auto Javascript Object]

**(PASS) new RTCPeerConnection("test")**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection(1)**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection(0)**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection(true)**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection(false)**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection([])**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection({})**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection({ iceServers: null })**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection({ iceServers: "test" })**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection({ iceServers: 1 })**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection({ iceServers: 0 })**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection({ iceServers: true })**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection({ iceServers: false })**
> Error: Failed to construct 'RTCPeerConnection': Malformed RTCConfiguration

**(PASS) new RTCPeerConnection({ iceServers: [] })**
> [JSAPI-Auto Javascript Object]

**(PASS) new RTCPeerConnection({ iceServers: [] }, null)**
> [JSAPI-Auto Javascript Object]

**(PASS) new RTCPeerConnection({ iceServers: [] }, undefined)**
> [JSAPI-Auto Javascript Object]

**(PASS) new RTCPeerConnection({ iceServers: [] }, {})**
> [JSAPI-Auto Javascript Object]

**(PASS) new RTCPeerConnection({ iceServers: [] }, { test: "x" })**
> [JSAPI-Auto Javascript Object]

**(PASS) new RTCPeerConnection({ iceServers: [] }, 1)**
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, 2)**
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, true)**
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, false)**
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, 0)**
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, [])
> [JSAPI-Auto Javascript Object]

**(PASS) new RTCPeerConnection({ iceServers: [] }, { optional: [] })**
> [JSAPI-Auto Javascript Object]

**(PASS) new RTCPeerConnection({ iceServers: [] }, { optional: "test" })**
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, { optional: 0 })**
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, { optional: 1 })**
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, { optional: true })**
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, { optional: false })**
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, { optional: {} })**
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, { optional: null })**
> [JSAPI-Auto Javascript Object]

**(PASS) new RTCPeerConnection({ iceServers: [] }, { optional: undefined })**
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(?) new RTCPeerConnection({ iceServers: [] }, { mandatory: {} })**
> [JSAPI-Auto Javascript Object]

**(?) new RTCPeerConnection({ iceServers: [] }, { mandatory: [] })**
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, { mandatory: "test" })**
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, { mandatory: 1 })**
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, { mandatory: 0 })**
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, { mandatory: null })**
> [JSAPI-Auto Javascript Object]

**(FAIL) new RTCPeerConnection({ iceServers: [] }, { mandatory: undefined })**
> TypeError: undefined is not an object (evaluating 'constraints.mandatory.constructor')

**(PASS) new RTCPeerConnection({ iceServers: [] }, { optional: "test", mandatory: [] })**
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(PASS) new RTCPeerConnection({ iceServers: [] }, { optional: [], mandatory: "test" })**
> Error: Failed to construct 'RTCPeerConnection': Malformed constraints object

**(?) new RTCPeerConnection({ iceServers: [] }, { optional: [], mandatory: {} })**
> [JSAPI-Auto Javascript Object]

**(PASS) new RTCPeerConnection({ iceServers: [] }, { optional: [], mandatory: null })**
> [JSAPI-Auto Javascript Object]

**Comment by johache** [comment]
* (?) new RTCPeerConnection({ iceServers: [] }, { mandatory: {} })
Should pass and passes

* (?) new RTCPeerConnection({ iceServers: [] }, { mandatory: [] })
Should fail and fails

* (?) new RTCPeerConnection({ iceServers: [] }, { optional: [], mandatory: {} })
Should pass and passes

(FAIL) new RTCPeerConnection({ iceServers: [] }, { mandatory: undefined })
should pass, corrected, same thing for new RTCPeerConnection({ iceServers: [] }, { optional: undefined })
Chrome doesn't pass, but I think it should, especially since the plugin can take it, and so does FF

**Comment by letchoo** [comment]
@johache up to you to decide if you think this behaviour is best, although I think that `null` and `undefined` should throw an error, and `mandatory` or `optional` should be consistent if it allows `{}` or `[]` or both.

**Comment by letchoo** [comment]
@johache if you think it's good to go, you can merge it.

**Comment by johache** [comment]
Will resolve the conflicts and merge today

**Pull request merged**
